# Site settings
title: DR Blog
SEOTitle: 梦曦的博客 | DR Blog
header-img: img/post-bg-desk.jpg
email: kodunull@gmail.com
description: "Every failure is leading towards success."
keyword: "DR, DR Blog,梦曦的博客, DestinyEnvoy"
url: "http://destinyenvoy.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/qiubaiying/qiubaiying.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about-DR-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: true
# weibo_username:     qiubaiying
#zhihu_username:     qiubaiying
github_username:    DestinyEnvoy
facebook_username: kodunull
jianshu_username:   DestinyEnvoy
twitter_username:   DestinyEnvoy

#替换默认的Markdown引擎为kramdown
#markdown: kramdown


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
 input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
#disqus_username: DestinyEnvoy

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: f3d3bccc3d5c3ede5e2d                            #生成的clientID
  clientSecret: 04851501589e9e753dfdad28a03aed1511b2d088    #生成的clientSecret
  repo: DestinyEnvoy.github.io    #仓库名称
  owner: DestinyEnvoy   #github用户名
  admin: DestinyEnvoy
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-145093117-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true




# Friends
friends: [
    {
        title: "WY",
        href: "http://zhengwuyang.com"
    },{
        title: "简书·BY",
        href: "http://www.jianshu.com/u/e71990ada2fd"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
