# Site settings
title: BugMan
SEOTitle: BugMan Blog
header-img: img/post-bg-desk.jpg
email: bugman.apt@gmail.com
description: "Every failure is leading towards success."
keyword: "Go, BugMan Blog, BugMan|Python"
url: "http://8gm.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/8gm/8gm.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "要努力使每一天都开心而有意义，不为别人，为自己."
sidebar-avatar: /img/bugman-header.jpg     # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: true
# weibo_username:     qiubaiying
zhihu_username:     
github_username:  jxysir
facebook_username:  
jianshu_username:   BugMan_Sec
twitter_username:   boss@Bypass_sec



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 79bce337a01c03697853                            #生成的clientID
  clientSecret: c43dd1586b53252bc378ed438595590ce176aa03    #生成的clientSecret
  repo: 8gm.github.io    #仓库名称
  owner: 8gm    #github用户名
  admin: 8gm
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
#Baidu Analytics
ba_track_id: 2c9591bfe18d9396e6f007f8377ede29

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# 友情链接
friends: [
    {
        title: "安全师",
        href: "https://www.secshi.com/"
    },{
        title: "lionking",
        href: "https://lionking.top/"
    },{
        title: "KAT",
        href: "https://www.cnblogs.com/kat-sec"
    },{
        title: "Yang34",
        href: "https://www.cnblogs.com/Yang34/"
    },{
        title: "彭楷模",
        href: "https://kaimopeng.github.io/"
    },{
        title: "Noaccess",
        href: "https://noaccess.cn/"
    },{
        title: "Cnnb",
        href: "https://www.cnblogs.com/CNnb/"
    },{
        title: "简书",
        href: "https://www.jianshu.com/"
    },{
        title: "先知",
        href: "https://xz.aliyun.com/"
    },{
        title: "SEC-IN",
        href: "https://sec-in.com/"
    },{
        title: "SeeBug",
        href: "https://www.seebug.org/"
    },{
        title: "VirusTotal",
        href: "https://www.virustotal.com/"
    },{
        title: "CVE",
        href: "https://cve.mitre.org/"
    },{
        title: "CxSecurity",
        href: "https://cxsecurity.com/"
    }
]

