# Site settings
title: Boyan's Blog
SEOTitle: Boyan的博客 | Boyan Blog
header-img: img/post-bg-desk.jpg      #显示在首页的背景图片
email: qiubaiying@gmail.com
description: "We don't know what we don't know."
keyword: "NYU Shanghai, Software Engineering, Data Science, AI" #关键词
url: "https://boyanxu.github.io"          # your host, for absolute URL # 这个就是填写你的博客地址
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'  
github_repo: "https://github.com/qiubaiying/qiubaiying.github.io.git" # you code repository 

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "This is sidebar!"
sidebar-avatar: /img/about-Boyan-Avatar.jpeg      # 你的个人头像 # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     boyanxu
github_username:    BoyanXu
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: boyanxu

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 8cd9382c59bd8d19981d                            #生成的clientID
  clientSecret: 4dfb8f46bc2c45ea2e45fe13b3326cc1a898cb47    #生成的clientSecret
  repo: BoyanXu.github.io    #仓库名称
  owner: BoyanXu    #github用户名
  admin: ['BoyanXu']
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "WY",
        href: "http://zhengwuyang.com"
    },{
        title: "简书·BY",
        href: "http://www.jianshu.com/u/e71990ada2fd"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]

theme: jekyll-theme-cayman
