# Site settings
title: mijamind
SEOTitle: mijamind
header-img: img/home-bg.jpg
email: 13588034533@163.com
description: "A little knowledge is a dangerous thing."
keyword: "mijamind's Blog,关于程序设计,Software Engineer"
url: "http://Kernelresolution719.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Kernelresolution719/Kernelresolution719.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "The man was lazy, and left nothing<br>这个人很懒，什么也没留下!"
sidebar-avatar: /img/home-about-mijamind.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
github_username:    Kernelresolution719




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: fe3d9f40fbafc3c4374d                            #生成的clientID
  clientSecret: 69322467ca0dd221196a76bd7694ca3c22b74887    #生成的clientSecret
  repo: Kernelresolution719.github.io    #仓库名称
  owner: Kernelresolution719    #github用户名
  admin: Kernelresolution719
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计(暂不启用)

# Analytics settings
# Baidu Analytics
#ba_track_id: NULL

# Google Analytics
#ga_track_id: 'UA-NULL'            # Format: UA-xxxxxx-xx
#ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Huawei",
        href: "https://github.com/Huawei"
    }
]
